# Generated by Django 2.1.2 on 2018-11-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=100)),
                ('todo_content', models.TextField(null=True)),
                ('deadline', models.DateTimeField()),
                ('priority', models.IntegerField(default=3)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
